language: java
jdk: openjdk8
install: true
os: linux
dist: trusty
script:
  - "./gradlew build --scan -s"
  - "./gradlew sonarqube"
addons:
  sonarcloud:
    organization: nl-orangeflamingo
    token:
      secure: "mSDt0gtqnjip7Gx+pQdj6wGfaUjIKLXDCDHykVY5Cp2BV+8jw96pCy4zfmAZM6HjssslJUavPS5qt7OcJ75HzpJ6pXNPzx1uvRjmSZlIY8zeGtfls2aZp/WRB+331vHiqD8RXkQf1vchjTf2jViif7hxreClrDV81DjsoFGGGU9u9pwd5r+Ezw34HHBr+8dkZC5b7VJXN53I6qKWBbaH84HHzFZJhOxIuprKndxQ16GxTSShQOvJg0LweMDXv2hqlRgyF4UAxf9GEdXCOfMLcAn7jjzC18NuxUg5u69QK0cYnfaLud87FRdtjlucrzeLvufr2mOPGoz1NlizZZ5eRVByhWkX/d8EvmqPWFehUi4aFcF6phlm2Vx2iZTq++gbDgK08EBAi6rcwnMgv5F0kprp1nqWQE74MtG0Lxn1OZ52f6R9kAjbe0gsVEOt7P8YRtLtkjiDWQKS1MhiLTqLeTTieeAr9QIRN+iVEr2qSdeMzMM+gZ9zyyaDBAB5hnJIzBMWLALlTKaznCNBiG/uJCk3dZPG3S4F/Q2wLZIHVl9UCIT8q9rjYz2grXXiUSb+yOJNO4+tg6z0a9OveaOj2V7C48DWswINmE+EcjjJflyxi1NX/MhNVbIH8DW815gsda11gkihwDOUAc+0HaFKGpE6SVf5zxDg29VUxpuL8tc="
