server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: voornameninliedjes
      username: mongoadmin
      password: secret
      authentication-database: admin