server:
  port: 8082

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: voornameninliedjes
      username: mongoadmin
      password: secret
      authentication-database: admin

orangeflamingo:
  admin:
    user1: remco
    password1: secret
    user2: nadja
    password2: secret