server:
  port: 8082

spring:
  data:
    mongodb:
      auto-index-creation: false
      host: localhost
      port: 27017
      database: voornameninliedjes
      username: mongoadmin
      password: secret
      authentication-database: admin

orangeflamingo:
  admin:
    user1: remco
    password1: secret
    user2: nadja
    password2: secret

# These will be transferred to System properties, see https://docs.spring.io/spring-boot/docs/2.1.4.RELEASE/reference/html/boot-features-logging.html#boot-features-custom-log-configuration
# These systems properties are uses in log4j2 configuration
logging:
  file:
    path: logs