spring:
  profiles:
    active: development
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    initialize: true

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgresql
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voornameninliedjes
    username: postgres
    password: postgres

spring:
  profiles: prod
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgresql
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_DB_HOST}:${POSTGRES_DB_PORT}/voornameninliedjes
    username: ${POSTGRES_DB_USERNAME}
    password: ${POSTGRES_DB_PASSWORD}

# Logging
#logging:
#  level:
#    org:
#      hibernate:
#        type: trace
#
#spring:
#  jpa:
#    properties:
#      hibernate:
#        show_sql: true
#        format_sql: true

