spring:
  profiles: development
  h2:
    console:
      enabled: true
  datasource:
    platform: h2
    initialize: true

spring:
  profiles: test
  jpa:
    hibernate:
      ddl-auto: validate
  datasource:
    platform: postgresql
    initialize: false
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/voornameninliedjes
    username: postgres
    password: postgres
